// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContexts() {
  return window['go']['main']['App']['GetContexts']();
}

export function GetNamespaces() {
  return window['go']['main']['App']['GetNamespaces']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function ReadSecret(arg1, arg2) {
  return window['go']['main']['App']['ReadSecret'](arg1, arg2);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SetCurrentContext(arg1) {
  return window['go']['main']['App']['SetCurrentContext'](arg1);
}

export function SetCurrentNamespace(arg1) {
  return window['go']['main']['App']['SetCurrentNamespace'](arg1);
}
