// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetContexts():Promise<main.GetContextsResponse>;

export function GetNamespaces():Promise<main.GetNamespacesResponse>;

export function GetVersion():Promise<string>;

export function ListSecrets(arg1:string):Promise<main.ListSecretsResponse>;

export function ReadSecret(arg1:string,arg2:string):Promise<main.ReadSecretResponse>;

export function ReloadConfig():Promise<string>;

export function SetCurrentContext(arg1:string):Promise<string>;

export function SetCurrentNamespace(arg1:string):Promise<string>;
